services:
  api:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: mypassword
    ports:
      - "1433:1433"
